-- Tabla DE PRUEBA con nombre único para evitar conflictos
-- Nombre de la tabla: tabla_prueba_final
-- Todas las columnas son TEXT para asegurar que el CSV suba sin errores

DROP TABLE IF EXISTS tabla_prueba_final CASCADE;

CREATE TABLE tabla_prueba_final (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Cabeceras EXACTAS del CSV
    ruc TEXT,
    codigo_establecimiento_ruc TEXT,
    estado_ruc TEXT,
    nombre_comercial TEXT,
    numero_registro TEXT,
    fecha_registro TEXT,
    actividad_modalidad TEXT,
    clasificacion TEXT,
    categoria TEXT,
    razon_social_propietario TEXT,
    representante_legal TEXT,
    tipo_local TEXT,
    tipo_establecimiento TEXT,
    nombre_franquicia_cadena TEXT,
    tipo_personeria_juridica TEXT,
    personeria_juridica TEXT,
    provincia TEXT,
    canton TEXT,
    parroquia TEXT,
    tipo_parroquia TEXT,
    direccion TEXT,
    referencia_direccion TEXT,
    telefono_principal TEXT,
    telefono_secundario TEXT,
    latitud TEXT,
    longitud TEXT,
    correo_electronico TEXT,
    direccion_web TEXT,
    estado_registro_establecimiento TEXT,
    sistema_origen TEXT,
    estado_registro_con_deuda TEXT,
    total_trabajadores_hombres TEXT,
    total_trabajadores_mujeres TEXT,
    total_trabajadores_hombres_discapacidad TEXT,
    total_trabajadores_mujeres_discapacidad TEXT,
    total_trabajadores TEXT,
    total_habitaciones_tiendas TEXT,
    total_camas TEXT,
    total_plazas TEXT,
    total_capacidades_servicios_complementarios TEXT,
    total_mesas TEXT,
    total_capacidades_personas TEXT,
    titulo_habilitante TEXT,
    fecha_emision_titulo TEXT,
    fecha_caducidad_titulo TEXT,
    tipo_vehiculo TEXT,
    matricula TEXT,
    fecha_matricula TEXT,
    fecha_caducidad_matricula TEXT,
    capacidad_unidad TEXT,
    total_vehiculos TEXT,
    total_asientos_vehiculos TEXT,
    tipo_local_transporte TEXT,
    tipo_embarcaciones TEXT,
    modalidad_embarcaciones TEXT,
    matricula_embarcacion TEXT,
    total_capacidades_embarcaciones TEXT,
    total_capacidades_otras_actividades TEXT,
    anio_declaracion_tarifario TEXT,
    fecha_declaracion_tarifario TEXT,
    tipos_capacidades TEXT,
    cantidad_por_tipo_capacidad TEXT,
    plazas_por_tipo_capacidad TEXT,
    tarifa_por_tipo_capacidad TEXT,
    tipos_cocina TEXT,
    tipos_servicio TEXT,
    modalidades_turismo_aventura TEXT,
    actividades_permitidas_ctc TEXT,
    identificaciones_guias_turismo TEXT,
    nombres_guias_turismo TEXT,
    ruc_companias_transporte TEXT,
    razon_social_companias_transporte TEXT,
    identificaciones_representantes_ventas TEXT,
    nombres_representante_ventas TEXT,
    persona_contacto TEXT,
    correo_persona_contacto TEXT,
    tipo_tramite TEXT,
    fecha_tramite TEXT,
    modificacion_sistema TEXT,
    observaciones_modificacion_sistema TEXT,
    zona_turistica TEXT,
    administracion_zonal TEXT,
    sector_turistico TEXT,
    columna1 TEXT,
    columna2 TEXT,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Permisos totales
ALTER TABLE tabla_prueba_final ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acceso total prueba" ON tabla_prueba_final FOR ALL USING (true) WITH CHECK (true);
